version: "3.7"

services:
<<<<<<< HEAD

=======
>>>>>>> e961774bcf4ced03f48e4e32ce70cac322bc64e3
  db:
    image: postgres
    restart: always
    environment:
<<<<<<< HEAD
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: sequelize
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
volumes: 
  pgdata:
=======
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: devices
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
>>>>>>> e961774bcf4ced03f48e4e32ce70cac322bc64e3
