version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: devices
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
